language: python
sudo: false
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - pypy
#   - pypy3
#   pending 3.3-compatible release
install:
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then pip install bcrypt; fi
    - pip install .
script:
    - python setup.py test -q
notifications:
    email: false
